config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :doctors
  get 'doctor/index'

   root 'doctors#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_many :resumes
	has_many :procedures
	belongs_to :user
	has_many :tasks, inverse_of: :doctor
	accepts_nested_attributes_for :procedures, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :resumes, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
	has_attached_file :image, styles: { medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates  :name, :website, :phone, :title, presence: true


end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :doctor
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :doctor
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :doctor
	validates :doctor, presence: true
	validates  :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :tasks
         has_many :doctors
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)
    
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:id, :image, :name, :website, :phone, :title, tasks_attributes: [:id,:image, :description, :done, :_destroy], 
        resumes_attributes: [:id, :experience, :_destroy], procedures_attributes: [:id, :type_procedure, :_destroy] )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def action 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/doctors/_form.html.erb
<div class="container">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag @doctor.image.url(:medium) %>
    </a>
  </div>
  <div class="row">
  <div class="col-xs-6 col-md-5">

    <ul class="list-group">
      <li class="list-group-item"><h4><%= @doctor.name %></h4></li>
      <li class="list-group-item"><strong>Website: </strong><%= @doctor.website %></li>
      <li class="list-group-item"><strong>Phone: </strong> <%= @doctor.phone %></li>
      <li class="list-group-item"> <strong>Title: </strong><%= @doctor.title %></li>
    </ul>
  </div>
  <div class="row">
  <div class="col-xs-6 col-md-4">
    
  </div>
</div>
    

    

</div>


  </div>
</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">

<div class="row">
  <div class="container">
  <div class="col-md-6">
<%= simple_form_for(@doctor, html: { class: 'form-horizontal' }) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.file_field :image %>
  <%= f.input :name %>
  <%= f.input :website %>
  <%= f.input :phone %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>
</div>
</div>
</div>
</div>
</div>




<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">

  <div class="col-md-2"><strong>Cedula Profesional</strong></div>
<%= simple_form_for(@doctor, html: { class: 'form-horizontal' }) do |f| %>

<h3> Experience </h3>

  <div id="tasks" >
   <%= f.fields_for :tasks do |task| %>
     <%= render 'task_fields', f: task %>
  <% end %>
  <div class="links">
      <%= link_to_add_association 'add task', f, :tasks, class:"btn btn-default" %>

 <% end %>
 </div>
</div>
  </div>
 </div>


    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Procedures</strong></div>
    
 <%= simple_form_for(@doctor, html: { class: 'form-horizontal' }) do |f| %>

  <h3> Procedures </h3>
  <div id="procedures" >
   <%= f.fields_for :procedures do |procedure| %>
     <%= render 'procedure_fields', f: procedure %>
  <% end %>
  <div class="links">
   <%= link_to_add_association 'add procedure', f, :procedures, class:"btn btn-default" %>

 <% end %>
 </div>
</div>
  </div>
 </div>


    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Experience</strong></div>
    
 <%= simple_form_for(@doctor, html: { class: 'form-horizontal' }) do |f| %>

  <h3> Resume </h3>
  <div id="resume" >
   <%= f.fields_for :resumes do |resume| %>
     <%= render 'resume_fields', f: resume %>
  <% end %>
  <div class="links">
   <%= link_to_add_association 'add resume', f, :resumes, class:"btn btn-default" %>

 <% end %>
 </div>
</div>
  </div>
 </div>


    </div>
  </div>
</div>
</div>

app/views/doctors/_procedure_fields.html.erb
<div class="col-md-10">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Procedures</strong></div>
  <div class="col-md-2">
<div class="nested-fields">
 <%= f.input :type_procedure %>
 <%= link_to_remove_association "remove procedure", f %>
 </div>

 <%= f.button :submit %>
  </div>
 </div>


    </div>
  </div>
</div>
</div>
</div>

app/views/doctors/_resume_fields.html.erb
<div class="col-md-10">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Experience</strong></div>
  <div class="col-md-2">
  <div class="nested-fields">
 <%= f.input :experience %>
 <%= link_to_remove_association "remove resume", f %>
 </div>
<%= f.button :submit %>
  </div>
 </div>


    </div>
  </div>
</div>
</div>
</div>

app/views/doctors/_task_fields.html.erb
<div class="nested-fields">
 <%= f.input :description %>
 <%= link_to_remove_association "remove task", f %>
 </div>

 <%= f.button :submit %>

app/views/doctors/edit.html.erb
<div class="container">
	<h1>Doctor Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>
</div>

app/views/doctors/index.html.erb
<div class="container-fluid">
<div class="jumbotron">
  <div class="container">
  
  </div>
</div>
</div>
<div class="container-fluid">
  <div class="color-box">
    <div class="container">
<div class="row">
  <div class="col-xs-6 col-md-4"><span style="text-align:center;"><h2>Proyecto</h2></span></div>
  <div class="col-xs-12 col-md-8">
<p>NewCity Medical Plaza es el proyecto más innovador de Turismo Médico en México, se construye en la ciudad de Tijuana, B.C. a 500 metros de la frontera con San Diego para impulsar el Turismo de Salud en el Estado.</p>
<p>Nuestro objetivo es crear un proyecto integral con instalaciones de primer nivel, con amenidades y servicios que cubran TODAS las necesidades de nuestros médicos, pacientes y sus acompañantes</p></div>
  
</div>
  </div>
  </div>
</div>
<div class="container">
  <h1>Listing Doctors</h1>
  <p id="notice"><%= notice %></p>
<% @doctors.each_slice(3) do |doctor| %>
<div class="row">
  <% doctor.each do |doctors| %>
  <div class="col-md-4">
    
    <div class="thumbnail">
     <%= image_tag doctors.image.url , class:"img-thumbnail"%>
      <div class="caption">
        <h3><%= doctors.name %></h3>
        <td><%= doctors.website %></td>
        <td><%= doctors.phone %></td>
        <td><%= doctors.title %></td>
        <td><%= link_to 'Show', doctors %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctors, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <p><%= doctors.title %></p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        
    
      </div>

    </div>

  </div>
 <% end %>
</div>
 <% end %>
</div>
<div class="container-fluid">
  <div class="color-box">
    <div class="container">
      <div class="row">
  <div class="col-xs-6 col-sm-4"></div>
  <div class="col-xs-6 col-sm-4"><span style="text-align:center;"><h1>CONTÁCTANOS</h1></span></div>
  <!-- Optional: clear the XS cols if their content doesn't match in height -->
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-6 col-sm-4"></div>
</div>

  </div>
  </div>
</div>
<div class="container">
  <div class="row">
  <div class="col-xs-6">
<p>Gral. Manuel Márquez de León 1301,</p>
<p>Zona urbana Río Tijuana (frente Pueblo Amigo)</p>
<p>Tijuana, B.C. C.P. 22010</p>

<p><strong>Télefono: (664) 688 7357 | 01 800 4 HEALTH</strong></p>
<p>Email: ventas@newcitymed.com</p>

<p><strong><span style="color: #2a76af;">FROM USA</span></strong></p>
<p>Email: ventas@newcitymed.com</p>
<img src="images/newcity-b.jpg" alt="..." class="img-thumbnail">
</div>


  <div class="row">
    <div class="col-xs-6" >
    <form >
  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Email</label>
    <input type="email" class="form-control" id="exampleInputPassword1" placeholder="Email">
  </div>
 
  <button type="submit" class="btn btn-default">Submit</button>
</form>
    </div>
   </div>

</div>
</div>
</div>

app/views/doctors/new.html.erb
<div class="container">
	<h1>New Doctor</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<div class="container">
<div class="panel panel-default">
  <div class="panel-body">
  	<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag @doctor.image.url(:medium) %>
    </a>
  </div>
  <div class="row">
  <div class="col-xs-6 col-md-5">

    <ul class="list-group">
      <li class="list-group-item"><h4><%= @doctor.name %></h4></li>
      <li class="list-group-item"><strong>Website: </strong><%= @doctor.website %></li>
      <li class="list-group-item"><strong>Phone: </strong> <%= @doctor.phone %></li>
      <li class="list-group-item"> <strong>Title: </strong><%= @doctor.title %></li>
    </ul>
   <%= link_to 'Edit', edit_doctor_path(@doctor) %> |
   <%= link_to 'Back', doctors_path %>
  </div>
  <div class="row">
  <div class="col-xs-6 col-md-4">
    
  </div>
</div>
    

    

</div>


  </div>
</div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
  	<div class="row">
      <div class="color-box">
<h3 style="text-align:center;">Doctor Resume</h3>
      </div>

<div class="container">
  <div class="row">
  <div class="col-md-2" style="text-align:center;"><strong>Resumen Curricular</strong></div>
  <div class="col-md-4">
  <% @doctor.tasks.each do |t| %>
  <li><%= t.description %></li>
  <% end %>
</div>



</div>


  	</div>
  </div>
</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Procedures</strong></div>
  <div class="col-md-4">
  <% @doctor.procedures.each do |t| %>
  <li><%= t.type_procedure %></li>
  <% end %>
  </div>
 </div>


    </div>
  </div>
</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

<div class="container">
  <div class="row">
  <div class="col-md-2"><strong>Experience</strong></div>
  <div class="col-md-4">
  <% @doctor.resumes.each do |t| %>
  <li><%= t.experience %></li>
  <% end %>
  </div>
 </div>


    </div>
  </div>
</div>
</div>

app/views/layouts/_bottom.html.erb
<div class="footer">
  <div class="container">
	<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8"><h4>Newcity App <small>by Onixmediadesign</small></h4></div>
    <div class="col-xs-6 col-md-4"></div>
   </div> 
</div>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <div class="row">
    <div class="container">
  <div class="col-md-4"><img src="/images/logo.png" class="img-responsive" alt="Responsive image"></div>
  <div class="col-md-8">
  	<ul class="nav nav-pills">
  <li role="presentation" class="active"><%= link_to 'Home', root_path %></li>
  <li role="presentation"><a href="#">About</a></li>
  <li role="presentation"><a href="#">Find a Doctor</a></li>
  
<% if user_signed_in? %>  
  <li role="presentation"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
  <li role="presentation"><%= link_to 'New Doctor', new_doctor_path %></li>
  <% else %>
  <li role="presentation"><%= link_to 'Register', new_user_registration_path %></li>
  <li role="presentation"><%= link_to 'Log In', new_user_session_path %></li>

  <% end %> 
  
    </ul>
  </div>
   </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newcitymedapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %> 
<%= render 'layouts/slider' %>
  <div class="container-fluid">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-8"><p class="notice"><%= notice %></p></div>
        <div class="col-xs-6 col-md-4"><p class="alert"><%= alert %></p></div>
		   
       
     </div>
    </div>
             <div class="row">

     <%= yield %>

             </div>
   </div>
   <%= render 'layouts/bottom' %> 
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>